export const orders = [
  {
    id: 1,
    username: "John",
    userId: "1",
    email: "john@gmail.com",
    address: "Tokyo",
    phone: "090-2121-2233",
    productId: "1",
    productName: "Iphone 17 pro max",
    productImageUrl: "https://img1.kakaku.k-img.com/images/productimage/fullscale/J0000048756.jpg",
    price: 1000,
    variant: "#000",
    size: "45",
    status: "pending",
    isCompleted: false
  },
  {
    id: 1,
    username: "John",
    userId: "1",
    email: "john@gmail.com",
    address: "Tokyo",
    phone: "090-2121-2233",
    productId: "1",
    productName: "Iphone 17 pro max",
    productImageUrl: "https://img1.kakaku.k-img.com/images/productimage/fullscale/J0000048756.jpg",
    price: 1000,
    variant: "#000",
    size: "45",
    status: "pending",
    isCompleted: false
  },
  {
    id: 1,
    username: "John",
    userId: "1",
    email: "john@gmail.com",
    address: "Tokyo",
    phone: "090-2121-2233",
    productId: "1",
    productName: "Iphone 17 pro max",
    productImageUrl: "https://img1.kakaku.k-img.com/images/productimage/fullscale/J0000048756.jpg",
    price: 1000,
    variant: "#000",
    size: "45",
    status: "completed",
    isCompleted: true
  },
  {
    id: 1,
    username: "John",
    userId: "1",
    email: "john@gmail.com",
    address: "Tokyo",
    phone: "090-2121-2233",
    productId: "1",
    productName: "Iphone 17 pro max",
    productImageUrl: "https://img1.kakaku.k-img.com/images/productimage/fullscale/J0000048756.jpg",
    price: 1000,
    variant: "#000",
    size: "45",
    status: "pending",
    isCompleted: false
  },
]